import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
// The app's .js modules are ESM although the existing package is CommonJS.
const moduleURL=name=>'data:text/javascript;base64,'+Buffer.from(readFileSync(new URL(name,import.meta.url),'utf8')).toString('base64');
const outlineURL=moduleURL('./outline.js');
const {moveBranch,indentBranch,insertTask,removePreservingChildren,visibleTasks}=await import(outlineURL);
const {restoreDeleted,deletionRecord}=await import('data:text/javascript;base64,'+Buffer.from(readFileSync(new URL('./undo.js',import.meta.url),'utf8').replace("'./outline.js'",JSON.stringify(outlineURL))).toString('base64'));
const {parsePaste}=await import(moduleURL('./paste.js'));
const {toMarkdown}=await import(moduleURL('./markdown.js'));
const {searchCommands}=await import(moduleURL('./themes.js'));
const task=(id,depth=0)=>({id,text:id,depth,done:false});
const tasks=[task('parent'),task('a',1),task('grandchild',2),task('b',1),task('other')];
const shape=ts=>ts.map(t=>[t.id,t.depth]);
assert.deepEqual(shape(moveBranch(tasks,'a',1)),[['parent',0],['b',1],['a',1],['grandchild',2],['other',0]]);
assert.deepEqual(shape(moveBranch(tasks,'b',-1)),[['parent',0],['a',1],['b',2],['grandchild',2],['other',0]],'Up enters the preceding sublist');
assert.deepEqual(shape(moveBranch(tasks,'a',-1)),[['a',0],['grandchild',1],['parent',0],['b',1],['other',0]],'First child exits before its parent with descendants');
assert.deepEqual(shape(moveBranch(tasks,'b',1)),[['parent',0],['a',1],['grandchild',2],['b',0],['other',0]],'Last child exits after its parent');
assert.equal(moveBranch(tasks,'parent',-1),tasks);
assert.equal(moveBranch(tasks,'other',1),tasks);
assert.deepEqual(shape(moveBranch([task('before'),...tasks],'before',1)),[['parent',0],['before',1],['a',1],['grandchild',2],['b',1],['other',0]],'Down enters a neighboring sublist');
assert.deepEqual(shape(moveBranch([task('parent'),task('a',1),task('child',2)],'a',1)),[['parent',0],['a',0],['child',1]],'End of outline permits outdenting');
const validate=ts=>{assert.equal(ts[0].depth,0);for(let i=1;i<ts.length;i++)assert.ok(ts[i].depth<=ts[i-1].depth+1)};
for(const id of tasks.map(t=>t.id))for(const direction of [-1,1]){let moved=tasks;for(let i=0;i<30;i++){moved=moveBranch(moved,id,direction);validate(moved);assert.equal(new Set(moved.map(t=>t.id)).size,tasks.length)}}
const deep=Array.from({length:30},(_,i)=>task('n'+i,i));
const inserted=insertTask(deep,'n29',true,task('new'));
assert.equal(inserted.at(-1).depth,30);
const siblings=[...deep,task('sibling',29)];
assert.equal(indentBranch(siblings,'sibling',1).at(-1).depth,30);
const record=deletionRecord(deep,'n15');
assert.deepEqual(restoreDeleted(removePreservingChildren(deep,['n15']),record).map(t=>[t.id,t.depth]),deep.map(t=>[t.id,t.depth]));
const branchTasks=[task('before'),{...task('parent'),collapsed:true}, {...task('child',1),done:true},task('nested',2),task('after')];
const branchRecord=deletionRecord(branchTasks,'parent',[],true);
const withoutBranch=removePreservingChildren(branchTasks,branchRecord.branch.map(t=>t.id));
assert.deepEqual(withoutBranch.map(t=>t.id),['before','after']);
assert.deepEqual(restoreDeleted(withoutBranch,branchRecord),branchTasks,'Branch undo preserves all text, depths, completion and collapse state');
const nestedBranchRecord=deletionRecord(deep,'n15',[],true);
assert.deepEqual(restoreDeleted(removePreservingChildren(deep,nestedBranchRecord.branch.map(t=>t.id)),nestedBranchRecord),deep,'Undo restores arbitrary-depth sublists');
const changedNeighbors=withoutBranch.map(t=>t.id==='after'?{...t,text:'Edited after deletion'}:t);
assert.equal(restoreDeleted(changedNeighbors,branchRecord).at(-1).text,'Edited after deletion','Undo preserves edits to unrelated notes');
assert.equal(deletionRecord(branchTasks,'after',[],true).branch,null,'Leaf deletion is a single-note undo');
assert.equal(parsePaste(deep.map(t=>'  '.repeat(t.depth)+t.text).join('\n')).entries.at(-1).depth,29);
assert.ok(toMarkdown(deep).split('\n').at(-1).startsWith('  '.repeat(29)));
assert.deepEqual(visibleTasks(tasks.map(t=>t.id==='a'?{...t,collapsed:true}:t)).map(t=>t.id),['parent','a','b','other']);
assert.equal(searchCommands([{id:'action',label:'Add child to selected task',group:'Actions',disabled:true},{id:'note',label:'Child A',group:'Notes'}],'Child A')[0].id,'note');
console.log('Outline checks passed: movement across sublists, descendants, unlimited nesting, undo, paste, export, visibility, and note search.');
