import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
// The app's .js modules are ESM although the existing package is CommonJS.
const moduleURL=name=>'data:text/javascript;base64,'+Buffer.from(readFileSync(new URL(name,import.meta.url),'utf8')).toString('base64');
const outlineURL=moduleURL('./outline.js');
const {moveBranch,indentBranch,insertTask,removePreservingChildren,visibleTasks}=await import(outlineURL);
const {restoreDeleted,deletionRecord}=await import('data:text/javascript;base64,'+Buffer.from(readFileSync(new URL('./undo.js',import.meta.url),'utf8').replace("'./outline.js'",JSON.stringify(outlineURL))).toString('base64'));
const {parsePaste}=await import(moduleURL('./paste.js'));
const {toMarkdown}=await import(moduleURL('./markdown.js'));
const {searchCommands}=await import(moduleURL('./themes.js'));
const task=(id,depth=0)=>({id,text:id,depth,done:false});
const tasks=[task('parent'),task('a',1),task('grandchild',2),task('b',1),task('other')];
assert.deepEqual(moveBranch(tasks,'a',1).map(t=>t.id),['parent','b','a','grandchild','other']);
assert.deepEqual(moveBranch(tasks,'b',-1).map(t=>t.id),['parent','b','a','grandchild','other']);
assert.equal(moveBranch(tasks,'a',-1),tasks,'First child cannot escape its parent');
assert.equal(moveBranch(tasks,'b',1),tasks,'Last child cannot escape its parent');
assert.equal(moveBranch(tasks,'parent',-1),tasks);
assert.equal(moveBranch(tasks,'other',1),tasks);
assert.deepEqual(moveBranch(tasks,'parent',1).map(t=>t.id),['other','parent','a','grandchild','b']);
const deep=Array.from({length:30},(_,i)=>task('n'+i,i));
const inserted=insertTask(deep,'n29',true,task('new'));
assert.equal(inserted.at(-1).depth,30);
const siblings=[...deep,task('sibling',29)];
assert.equal(indentBranch(siblings,'sibling',1).at(-1).depth,30);
const record=deletionRecord(deep,'n15');
assert.deepEqual(restoreDeleted(removePreservingChildren(deep,['n15']),record).map(t=>[t.id,t.depth]),deep.map(t=>[t.id,t.depth]));
assert.equal(parsePaste(deep.map(t=>'  '.repeat(t.depth)+t.text).join('\n')).entries.at(-1).depth,29);
assert.ok(toMarkdown(deep).split('\n').at(-1).startsWith('  '.repeat(29)));
assert.deepEqual(visibleTasks(tasks.map(t=>t.id==='a'?{...t,collapsed:true}:t)).map(t=>t.id),['parent','a','b','other']);
assert.equal(searchCommands([{id:'action',label:'Add child to selected task',group:'Actions',disabled:true},{id:'note',label:'Child A',group:'Notes'}],'Child A')[0].id,'note');
console.log('Outline checks passed: branch boundaries, descendants, unlimited nesting, undo, paste, export, visibility, and note search.');
